### PR TITLE
Add css to hmtl files for v4.16.2, v4.15.0, v4.14.1, v4.13.0

### PR DESCRIPTION
**Pull request by coyotte508**
This should solve the css issues (spacing of the colab dropdown for example) in moon-landing on those versions of the doc.

You can test in your local moonlanding by switching the branch of `repos/doc-build` to `with-css`.

cc @Pierrci

### CODE REVIEW

**Comment by mishig25** [comment]
dont't merge it yet, I'm still seeing some css problems, will debug why

**Comment by Pierrci** [comment]
I tried w/ this branch but it seems the added CSS is basically ignored by the browser?

**Comment by Pierrci** [comment]
It seems to me that the entire additional CSS file is simply completely ignored currently - try commenting the import of the main CSS file in moon-landing in `layout.html`, and you can see it's as if there wasn't any CSS at all.

Try moving the additional CSS in the `head` of moon-landing manually, and it applies:
- with conflicts, if added _after_ the main CSS
- without conflicts (AFAICT), if added _before_ the main CSS

**Comment by coyotte508** [comment]
Maybe for the components we can use scoped css instead of tailwind :thinking:

**Pull request closed without merging**
